languageCode = "en"
languageName = "English"
weight = 1
title = "Raizen | Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "My awesome website"
dateFormat = "2 January 2006"
logo = "img/avatar.png"

[author]
name = "Rai2en"
image = "img/av.png"
headline = "Just a cybersecurity enthusiast"
bio = "Exploiting the unseen, mastering the unknown"
links = [ { email = "mailto:r4izen777@gmail.com" }, { github = "https://github.com/Rai2en" }, { linkedin = "https://www.linkedin.com/in/crispus-houessou/" }, { x-twitter = "https://x.com/0xR4zn" } ]
