[[main]]
  name = "Articles"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Sujets"
  pageRef = "topics"
  weight = 20

[[main]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 30

[[main]]
  name = "À propos"
  pageRef = "about"
  weight = 40

[[footer]]
  name = "Sujets"
  pageRef = "topics"
  weight = 10

[[footer]]
  name = "Portfolio"
  pageRef = "portfolio"
  weight = 20

[[footer]]
  name = "Catégories"
  pageRef = "categories"
  weight = 30
